apiVersion: v1
kind: Service
metadata:
  name: service-postgres
  labels:
    name: postgres
    env: prod
  namespace: ic-webapp
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
