apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    app: ic-webapp
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: abdoulayedevops/ic-webapp:v1
        ports:
        - containerPort: 8080
        env:
          - name: ODOO_URL
            value: http://192.168.56.105:30011
          - name: PGADMIN_URL
            value: http://192.168.56.105:30012