version: '3.3'
services:
  ic-webapp:
    image: abdoulayedevops/ic-webapp:v1
    container_name: ic-webapp
    depends_on:
      - odoo
      - pgadmin
    ports:
      - "8080:8080"
    environment:
      - ODOO_URL=http://192.168.56.104:8069
      - PGADMIN_URL=http://192.168.56.104:8070
    networks:
      - ic-network
  odoo:
    image: odoo:14.0
    container_name: odoo
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
      - HOST=postgres
    networks:
      - ic-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    volumes:
      -  $PWD/servers.json:/pgadmin4/servers.json
      -  pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=abdou@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "8070:80"
    networks:
      - ic-network
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - ic-network            
volumes:
  odoo-data:
  postgres-data:
  pgadmin-data:
networks:
  ic-network:
    driver: bridge
    name: ic-network